# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 304a809deaa5fc0421ca40fd333e91799e12ec6a212f24bbbe43f33adedcaf2152f5ca39aaa453d780d6660df29c93887e5a53f1c778e4e14a99a21885711666

test:
  secret_key_base: a293c3170b4f6d9ed9033e0291693e3b18c24ca8b530b739b6702908159ce060cce3701f5a047d4f4af286b91da15b02e38d611c163269e951aeaed1b7ca68a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
